export const COUNTRY_CODES = [
    { country: 'Nigeria', code: '+234', flag: '🇳🇬', iso: 'NG' },
    { country: 'United States', code: '+1', flag: '🇺🇸', iso: 'US' },
    { country: 'United Kingdom', code: '+44', flag: '🇬🇧', iso: 'GB' },
    { country: 'Canada', code: '+1', flag: '🇨🇦', iso: 'CA' },
    { country: 'Ghana', code: '+233', flag: '🇬🇭', iso: 'GH' },
    { country: 'South Africa', code: '+27', flag: '🇿🇦', iso: 'ZA' },
    { country: 'Kenya', code: '+254', flag: '🇰🇪', iso: 'KE' },
    { country: 'Germany', code: '+49', flag: '🇩🇪', iso: 'DE' },
    { country: 'France', code: '+33', flag: '🇫🇷', iso: 'FR' },
    { country: 'India', code: '+91', flag: '🇮🇳', iso: 'IN' },
    { country: 'China', code: '+86', flag: '🇨🇳', iso: 'CN' },
    { country: 'Australia', code: '+61', flag: '🇦🇺', iso: 'AU' },
    { country: 'Brazil', code: '+55', flag: '🇧🇷', iso: 'BR' },
    { country: 'Russia', code: '+7', flag: '🇷🇺', iso: 'RU' },
    { country: 'Japan', code: '+81', flag: '🇯🇵', iso: 'JP' },
    { country: 'Cameroon', code: '+237', flag: '🇨🇲', iso: 'CM' },
    { country: 'Ivory Coast', code: '+225', flag: '🇨🇮', iso: 'CI' },
    { country: 'Senegal', code: '+221', flag: '🇸🇳', iso: 'SN' },
    { country: 'Uganda', code: '+256', flag: '🇺🇬', iso: 'UG' },
    { country: 'Egypt', code: '+20', flag: '🇪🇬', iso: 'EG' },
];
